# Generated by Django 4.2 on 2025-04-16 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('info', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('urgent', models.BooleanField(default=False)),
                ('has_photo', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('REAL_ESTATE', 'Real Estate'), ('VEHICLES', 'Vehicles'), ('DIGITAL_GOODS', 'Digital Goods'), ('HOME_KITCHEN', 'Home Kitchen'), ('SERVICES', 'Services'), ('PERSONAL_ITEMS', 'Personal Item'), ('ENTERTAINMENT_LEISURE', 'Entertainment Leisure'), ('COMMUNITY', 'Community'), ('INDUSTRIAL EQUIPMENT', 'Industrial Equipment'), ('JOBS & EMPLOYMENT', 'Jobs Employment')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
